command:
  - "bash"
  - "start.sh"

env:
  - name: APP_ENV
    value: "production"
  - name: DATABRICKS_CLUSTER_ID
    value: "0402-042550-3eto1bj6"
  - name: LLM_ENDPOINT_NAME
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: UC_CATALOG
    value: "dbw_vectoflow_dev"
  - name: UC_DISCOVERY_SCHEMA
    value: "vectoflow"
  - name: UC_OUTPUT_SCHEMA
    value: "ml_accelerator"
  - name: DATABRICKS_SECRET_SCOPE
    value: "vectoflow-secret-scope"
  - name: DATABRICKS_SECRET_KEY
    value: "vectoflow_pat"
  - name: AUTH_TYPE
    value: "oauth"
  - name: DATABRICKS_CONFIG_FILE
    value: "/dev/null"
  - name: API_BASE
    value: "http://127.0.0.1:8080"
  - name: SQL_WAREHOUSE_ID
    value: "cd22865cf1b63262"
  - name: LAKEBASE_ENDPOINT_NAME
    value: "projects/ml-accelerator/branches/production/endpoints/primary"
  - name: LAKEBASE_HOST
    value: "ep-long-bread-e91mfyha.database.eastus.azuredatabricks.net"
  - name: LAKEBASE_USER
    value: "98732ce4-1f2d-4768-bbb2-caa6bd246b37"
  - name: LAKEBASE_DATABASE
    value: "databricks_postgres"
