"""
Writes generated notebooks and job YAMLs to the Databricks Asset Bundle structure.

bundles/
├── src/
│   └── {use_case_slug}/
│       ├── 01_feature_engineering.py
│       ├── 02_training.py
│       └── 03_batch_inference.py
└── resources/
    └── jobs/
        ├── {use_case_slug}_feature_pipeline_job.yml
        ├── {use_case_slug}_training_job.yml
        └── {use_case_slug}_batch_inference_job.yml
"""

import logging
import os
import re
from pathlib import Path

from agent.state import GeneratedArtifact

logger = logging.getLogger(__name__)

BUNDLES_ROOT = Path(__file__).parent.parent / "bundles"


def slugify(name: str) -> str:
    """Convert use case name to a safe filesystem + YAML identifier."""
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug


def write_artifacts(artifacts: list[GeneratedArtifact]) -> list[str]:
    """
    Write all generated artifacts to the bundles/ directory.
    Returns list of written file paths (relative to project root).
    """
    written = []
    for artifact in artifacts:
        dest = BUNDLES_ROOT / artifact["filepath"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(artifact["content"], encoding="utf-8")
        logger.info("Wrote: %s", dest)
        written.append(str(dest.relative_to(BUNDLES_ROOT.parent)))
    return written


def build_job_yaml(
    use_case_slug: str,
    job_type: str,                  # "feature_pipeline" | "training" | "batch_inference"
    notebook_relative_path: str,    # relative to bundles/ root
    cluster_id: str,
    catalog: str,
    output_schema: str,
    feature_table_name: str,
    model_name: str,
    scores_table_name: str,
) -> str:
    """
    Build a DAB job YAML string for a given notebook.
    All job params passed as notebook_params so the notebook receives them via dbutils.widgets.
    """
    params: dict[str, str] = {
        "catalog": catalog,
        "output_schema": output_schema,
        "feature_table_name": feature_table_name,
        "model_name": model_name,
        "scores_table_name": scores_table_name,
    }

    schedule_map = {
        "feature_pipeline": "0 0 2 * * ?",   # 02:00 UTC daily
        "training": "0 0 4 ? * SUN",          # 04:00 UTC weekly on Sunday
        "batch_inference": "0 0 6 * * ?",     # 06:00 UTC daily (after feature pipeline)
    }

    notebook_params_yaml = "\n".join(
        f'          {k}: "{v}"' for k, v in params.items()
    )

    return f"""# Auto-generated by Databricks ML Accelerator
# Use case: {use_case_slug} | Job: {job_type}
# Deploy with: databricks bundle deploy --target dev

resources:
  jobs:
    {use_case_slug}_{job_type}_job:
      name: "{use_case_slug}_{job_type}"
      tasks:
        - task_key: {job_type}
          notebook_task:
            notebook_path: ../src/{use_case_slug}/{_notebook_name(job_type)}
            base_parameters:
{notebook_params_yaml}
          existing_cluster_id: "{cluster_id}"
          timeout_seconds: 3600
          retry_on_timeout: true
          max_retries: 2
          min_retry_interval_millis: 300000
      schedule:
        quartz_cron_expression: "{schedule_map[job_type]}"
        timezone_id: "UTC"
        pause_status: PAUSED
      email_notifications:
        on_failure: []
      tags:
        generated_by: databricks-ml-accelerator
        use_case: {use_case_slug}
"""


def _notebook_name(job_type: str) -> str:
    return {
        "feature_pipeline": "01_feature_engineering",
        "training": "02_training",
        "batch_inference": "03_batch_inference",
    }[job_type]


def prepare_artifacts_from_generation(
    use_case_slug: str,
    notebook_contents: dict[str, str],   # {"01_feature_engineering": "...", "02_training": "...", ...}
    cluster_id: str,
    catalog: str,
    output_schema: str,
    feature_table_name: str,
    model_name: str,
    scores_table_name: str,
) -> list[GeneratedArtifact]:
    """
    Package generated notebook strings + build job YAMLs into GeneratedArtifact list.
    """
    artifacts: list[GeneratedArtifact] = []
    notebook_map = {
        "01_feature_engineering": "feature_pipeline",
        "02_training": "training",
        "03_batch_inference": "batch_inference",
    }

    # Notebooks
    for nb_key, job_type in notebook_map.items():
        content = notebook_contents.get(nb_key, "")
        if content:
            artifacts.append(GeneratedArtifact(
                filename=f"{nb_key}.py",
                filepath=f"src/{use_case_slug}/{nb_key}.py",
                content=content,
            ))

    # Job YAMLs
    for job_type in ["feature_pipeline", "training", "batch_inference"]:
        yaml_content = build_job_yaml(
            use_case_slug=use_case_slug,
            job_type=job_type,
            notebook_relative_path=f"src/{use_case_slug}/{_notebook_name(job_type)}",
            cluster_id=cluster_id,
            catalog=catalog,
            output_schema=output_schema,
            feature_table_name=feature_table_name,
            model_name=model_name,
            scores_table_name=scores_table_name,
        )
        artifacts.append(GeneratedArtifact(
            filename=f"{use_case_slug}_{job_type}_job.yml",
            filepath=f"resources/jobs/{use_case_slug}_{job_type}_job.yml",
            content=yaml_content,
        ))

    return artifacts
